apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels: 
    app: myapp
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        app: myapp
    spec: 
      containers: 
      - name: myapp-conatiner
        image: in28min/hello-world-rest-api:0.0.1.RELEASE
        ports: 
        - containerPort: 80
