apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: {app.kubernetes.io/managed-by: graphite-jenkins-gke}
spec:
  selector: {app: myapp}
  type: LoadBalancer
  ports:
  - {protocol: TCP, port: 80, targetPort: 8080}
